Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.synced_folder "../mount/", "/opt/mount"
  config.vm.provision "shell", inline: "/bin/bash /opt/mount/init.sh"
end